title: Seungeon's blog
include:
  - docs
theme: just-the-docs
lang: en
timezone: Asia/Seoul
social:
  email: djs9844@naver.com
  name: SeungeonEonJi
paginate: 5
nav_enabled: true
#color_scheme: dark

# Markdown and syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Mermaid support
mermaid: true
mermaid:
  version: "10.6.1"
